const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateMonthlyReport = async (financialData, month, year) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ size: 'A4', margin: 50 });

            // Temp folder එක
            const tempDir = path.join(__dirname, '../temp');
            if (!fs.existsSync(tempDir)) {
                fs.mkdirSync(tempDir, { recursive: true });
            }

            const fileName = `Deewaraya_Report_${month}_${year}_${Date.now()}.pdf`;
            const filePath = path.join(tempDir, fileName);
            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // ===== PDF Content =====

            // Title
            doc.fontSize(22).font('Helvetica-Bold')
               .fillColor('#1a5276')
               .text('DEEWARAYA', { align: 'center' });
            
            doc.fontSize(16).fillColor('#333333')
               .text('Monthly Financial Report', { align: 'center' });
            
            doc.moveDown(0.5);
            doc.fontSize(13).fillColor('#555555')
               .text(`${month} - ${year}`, { align: 'center' });
            
            doc.moveDown(1);
            doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#1a5276').stroke();
            doc.moveDown(1);

            // Summary Box
            doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a5276')
               .text('SUMMARY');
            doc.moveDown(0.5);

            doc.fontSize(12).font('Helvetica');
            doc.fillColor('#27ae60')
               .text(`Total Income:     Rs. ${financialData.totalIncome.toLocaleString()}`);
            doc.fillColor('#e74c3c')
               .text(`Total Expense:    Rs. ${financialData.totalExpense.toLocaleString()}`);
            doc.moveDown(0.3);
            
            const balance = financialData.totalIncome - financialData.totalExpense;
            doc.font('Helvetica-Bold')
               .fillColor(balance >= 0 ? '#27ae60' : '#e74c3c')
               .text(`Net Balance:      Rs. ${balance.toLocaleString()}`);
            
            doc.moveDown(1.5);
            doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke();
            doc.moveDown(1);

            // Transactions Table
            doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a5276')
               .text('TRANSACTIONS');
            doc.moveDown(0.5);

            // Table Header
            const headerY = doc.y;
            doc.fontSize(10).font('Helvetica-Bold').fillColor('#ffffff');
            
            // Header background
            doc.rect(50, headerY - 3, 495, 18).fill('#1a5276');
            doc.fillColor('#ffffff');
            doc.text('Date', 55, headerY);
            doc.text('Description', 150, headerY);
            doc.text('Type', 350, headerY);
            doc.text('Amount (Rs.)', 440, headerY);
            
            doc.moveDown(1);

            // Table Rows
            doc.font('Helvetica').fontSize(10);
            if (financialData.transactions && financialData.transactions.length > 0) {
                financialData.transactions.forEach((txn, index) => {
                    if (doc.y > 720) {
                        doc.addPage();
                    }

                    // Alternate row background
                    if (index % 2 === 0) {
                        doc.rect(50, doc.y - 3, 495, 16).fill('#f2f3f4');
                    }

                    const rowY = doc.y;
                    doc.fillColor('#333333');
                    doc.text(txn.date, 55, rowY);
                    doc.text(txn.description, 150, rowY);
                    doc.fillColor(txn.type === 'Income' ? '#27ae60' : '#e74c3c')
                       .text(txn.type, 350, rowY);
                    doc.text(txn.amount.toLocaleString(), 440, rowY);
                    doc.moveDown(0.5);
                });
            } else {
                doc.fillColor('#999999')
                   .text('No transactions found for this month.', 50, doc.y, { align: 'center' });
            }

            // Footer
            doc.moveDown(3);
            doc.fontSize(8).fillColor('#999999')
               .text('This report was auto-generated by Deewaraya System.', 50, 760, { align: 'center' });
            doc.text(`Generated on: ${new Date().toLocaleString()}`, 50, 772, { align: 'center' });

            doc.end();

            stream.on('finish', () => resolve(filePath));
            stream.on('error', (err) => reject(err));

        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generateMonthlyReport };